import axios from 'axios'
import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { GetServerSideProps } from 'next'
import { useSession, getSession  } from 'next-auth/react'

import AddNewTask from '../components/AddNewTask'
import TasksList from '../components/TaskList'
import Navigation from '../components/Navigation'

import { ITask } from '../models/Task'

type HomeProps = {
  tasks: ITask[]
}

const Home: NextPage<HomeProps> = ({tasks}) => {
  const { data: session } = useSession()

  return (
    <div className={styles.container}>
      <Head>
        <title>ToDo App with NextJs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <h1>ToDo NextJs App</h1>
      <AddNewTask />
      <TasksList tasks={tasks} />
    </div>
  )
}

export default Home

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession(context)

  if (!session) {
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      },
    }
  }

  if(session) {
    const res = await axios.request({
      url: 'http://localhost:3000/api/tasks',
      method: 'GET',
      decompress: false,
      data: session.user
    })

    return {
      props: {
        tasks: res.data
      }
    }
  } else {
    return {
      notFound: true
    }

  }
}



// export const getStaticProps: GetStaticProps = async (context) => {
//   const res = await axios.get('http://localhost:3000/api/tasks')

//   return {
//     props: {
//       tasks: res.data
//     }
//   }
// }